### ISSUE TITLE
Adding a RxSwift extension no longer recognized

### ISSUE THREAD

**Issue by aharriscrowne** [DenHeadless/DTModelStorage#22]
Using the v.6 beta1 build, code that incorporated RxSwift capabilities fails to build.
using:
`extension Reactive where Base : DTTableViewManager {
    func items<T>() -> UIBindingObserver<Base,[T]> {
        return UIBindingObserver(UIElement: base) { manager, array in
            manager.memoryStorage.setItems(array)
        }
    }
}
`

and referencing the resulting rx property of the manager returns a the following build error:
Value of type 'DTTableViewManager' has no member 'rx'

Switching back to version 5 eliminates this error but is not compatible with Xcode 9 Swift 3.2+

**Comment by DenHeadless** [comment]
@aharriscrowne This was a tricky one, initially i had no idea what is going on.

It turns out, that in 6.0.0 I removed NSObject inheritance from DTTableViewManager and DTCollectionViewManager, so they are now pure Swift objects without Objective-C. However, this also means, that they no longer conform to `ReactiveCompatible` protocol, that Rx uses for Reactive extensions. So, in order to write such extension, you now need to add this conformance explicitly:

```swift
extension DTTableViewManager: ReactiveCompatible {}
```

Hope this helps.
