### ISSUE TITLE
ReloadItem shows weird animation for the table.

### ISSUE THREAD

**Issue by ambujshukla** [DenHeadless/DTModelStorage#27]
Hi, when I try to reload the table for a particular cell then it shows weird animation. I am using this line to reload the item :- "storage.reloadItem(model1)".

When I execute this line "storage.reloadItem(model1)" and if that cell is at top then it comes little down and if it is in bottom then it shifts upwards. Can you please have a look?

**Comment by DenHeadless** [comment]
Hi!

This call is translated directly to UIKit API, in order to give you more context, in UITableView world this turns into:

```swift
tableView.reloadRows(at: [indexPath], with: animation)
```
`animation` in this case it set on `TableViewUpdater` - `reloadRowAnimation`, which is .automatic by default.

and in UICollectionView it turns into:

```swift
collectionView.reloadItems(at: [indexPath])
```

In case of UITableView you can try setting different animation type, that you may want. Generally, in my use cases, when i want to update table without animations, I actually use `setItems` directly, which leads to `reloadData` without animations, since `reloadItem` animations are kinda weird on `UITableView` side.

**Comment by ambujshukla** [comment]
Thanks @DenHeadless , it is working now. Instead of the reloadItem I just updated the particular model.
